export const horoscopeMessages = {
  dailyFound: "Found daily horoscope",
  dailyLoading: "Loading daily horoscopes...",
  dailyCreatingLoading: "Creating daily horoscope...",
  dailyUpdatingLoading: "Updating daily horoscope...",
  dailyError: "Error fetching daily horoscopes",
  dailyCreated: "Created daily horoscope",
  dailyUpdated: "Updated daily horoscope",
  dailyDeleted: "Deleted daily horoscope",
  dailyDelete: "Delete daily",
  dailyNotFound: "Not found daily horoscope",
  dailyCreate: "Create daily",
  dailyUpdate: "Update daily",
  missingHoroscopeId: "Please select a horoscope" ,
  missingStory: "Please provide a story",
  missingDate: "Date must be a future date",
  missingSign: "Please provide a sign",
  missingDescription: "Please provide a description",
  compatibilityCreated: "Created compatibility",
  compatibilityUpdated: "Compatiblity updated",
  compatibilityLoading: "Loading compatibilities...",
  compatibilityError: "Error fetching compatibilities",
  compatibilityNotFound: "Not found compatibilities",
  compatibilityCreate: "Create compatibility",
  compatibilityUpdate: "Update compatibility",

};
