import { PrismaClient } from "@prisma/client";
const prismadb = new PrismaClient();

async function main() {
  await prismadb.horoscope.createMany({
    data: [
      {
        sign: 'Aries',
        description: 'MUL LU.ḪUN.GA "Agrarian Worker", Dumuzi',
        gloss: 'The Ram',
        enum: 'ARIES',
        dateStart: new Date('2024-03-21'),
        dateEnd: new Date('2024-04-20'),
        eclipticLongitudeA: 0,
        eclipticLongitudeB: 30,
        polarity: 'Positive',
        element: 'Fire',
        planet: 'Mars',
        sexDrive: 'Masculine',
        hustle: 'Cardinal',
        vibe: 'Active',
        success: 'Initiating',
      },
      {
        sign: 'Taurus',
        description: 'MULGU4.AN.NA "Divine Bull of Heaven"',
        gloss: 'The Bull',
        enum: 'TAURUS',
        dateStart: new Date('2024-04-21'),
        dateEnd: new Date('2024-05-20'),
        eclipticLongitudeA: 30,
        eclipticLongitudeB: 60,
        polarity: 'Negative',
        element: 'Earth',
        planet: 'Venus',
        sexDrive: 'Feminine',
        hustle: 'Fixed',
        vibe: 'Receptive',
        success: 'Stabilizing',
      },
      {
        sign: 'Gemini',
        description: 'MULMAŠ.TAB.BA.GAL.GAL "Great Twins" (Castor & Pollux)',
        gloss: 'The Twins',
        enum: 'GEMINI',
        dateStart: new Date('2024-05-21'),
        dateEnd: new Date('2024-06-20'),
        eclipticLongitudeA: 60,
        eclipticLongitudeB: 90,
        polarity: 'Positive',
        element: 'Air',
        planet: 'Mercury',
        sexDrive: 'Masculine',
        hustle: 'Mutable',
        vibe: 'Adaptable',
        success: 'Changing',
      },
      {
        sign: 'Cancer',
        description: 'MULAL.LUL "Crayfish"',
        gloss: 'The Crab',
        enum: 'CANCER',
        dateStart: new Date('2024-06-21'),
        dateEnd: new Date('2024-07-22'),
        eclipticLongitudeA: 90,
        eclipticLongitudeB: 120,
        polarity: 'Negative',
        element: 'Water',
        planet: 'Moon',
        sexDrive: 'Feminine',
        hustle: 'Cardinal',
        vibe: 'Active',
        success: 'Initiating',
      },
      {
        sign: 'Leo',
        description: 'MULUR.GU.LA "Lion"',
        gloss: 'The Lion',
        enum: 'LEO',
        dateStart: new Date('2024-07-23'),
        dateEnd: new Date('2024-08-22'),
        eclipticLongitudeA: 120,
        eclipticLongitudeB: 150,
        polarity: 'Positive',
        element: 'Fire',
        planet: 'Sun',
        sexDrive: 'Masculine',
        hustle: 'Fixed',
        vibe: 'Receptive',
        success: 'Stabilizing',
      },
      {
        sign: 'Virgo',
        description: 'MULAB.SIN "The Furrow"* *"The goddess Shala\'s ear of grain"',
        gloss: 'The Maiden',
        enum: 'VIRGO',
        dateStart: new Date('2024-08-23'),
        dateEnd: new Date('2024-09-22'),
        eclipticLongitudeA: 150,
        eclipticLongitudeB: 180,
        polarity: 'Negative',
        element: 'Earth',
        planet: 'Mercury',
        sexDrive: 'Feminine',
        hustle: 'Mutable',
        vibe: 'Adaptable',
        success: 'Changing',
      },
      {
        sign: 'Libra',
        description: 'MULZIB.BA.AN.NA "Scales"',
        gloss: 'The Scales',
        enum: 'LIBRA',
        dateStart: new Date('2024-09-23'),
        dateEnd: new Date('2024-10-22'),
        eclipticLongitudeA: 180,
        eclipticLongitudeB: 210,
        polarity: 'Positive',
        element: 'Air',
        planet: 'Venus',
        sexDrive: 'Masculine',
        hustle: 'Cardinal',
        vibe: 'Active',
        success: 'Initiating',
      },
      {
        sign: 'Scorpio',
        description: 'MULGIR.TAB "Scorpion"',
        gloss: 'The Scorpion',
        enum: 'SCORPIO',
        dateStart: new Date('2024-10-23'),
        dateEnd: new Date('2024-11-21'),
        eclipticLongitudeA: 210,
        eclipticLongitudeB: 240,
        polarity: 'Negative',
        element: 'Water',
        planet: 'Mars',
        sexDrive: 'Feminine',
        hustle: 'Fixed',
        vibe: 'Receptive',
        success: 'Stabilizing',
      },
      {
        sign: 'Sagittarius',
        description: 'MULPA.BIL.SAG, Nedu "soldier"',
        gloss: 'The Archer (Centaur)',
        enum: 'SAGITTARIUS',
        dateStart: new Date('2024-11-22'),
        dateEnd: new Date('2024-12-21'),
        eclipticLongitudeA: 240,
        eclipticLongitudeB: 270,
        polarity: 'Positive',
        element: 'Fire',
        planet: 'Jupiter',
        sexDrive: 'Masculine',
        hustle: 'Mutable',
        vibe: 'Adaptable',
        success: 'Changing',
      },
      {
        sign: 'Capricorn',
        description: 'MULSUḪUR.MAŠ "Goat-Fish" of Enki',
        gloss: 'The Goat',
        enum: 'CAPRICORN',
        dateStart: new Date('2024-12-22'),
        dateEnd: new Date('2025-01-19'),
        eclipticLongitudeA: 270,
        eclipticLongitudeB: 300,
        polarity: 'Negative',
        element: 'Earth',
        planet: 'Saturn',
        sexDrive: 'Feminine',
        hustle: 'Cardinal',
        vibe: 'Active',
        success: 'Initiating',
      },
      {
        sign: 'Aquarius',
        description: 'MULGU.LA "Great One", later qâ "pitcher"',
        gloss: 'The Water-bearer',
        enum: 'AQUARIUS',
        dateStart: new Date('2025-01-20'),
        dateEnd: new Date('2025-02-18'),
        eclipticLongitudeA: 300,
        eclipticLongitudeB: 330,
        polarity: 'Positive',
        element: 'Air',
        planet: 'Saturn',
        sexDrive: 'Masculine',
        hustle: 'Fixed',
        vibe: 'Receptive',
        success: 'Stabilizing',
      },
      {
        sign: 'Pisces',
        description: 'MULSIM.MAḪ "Tail of the Swallow"; DU.NU.NU "fish-cord"',
        gloss: 'The Fish',
        enum: 'PISCES',
        dateStart: new Date('2025-02-19'),
        dateEnd: new Date('2025-03-20'),
        eclipticLongitudeA: 330,
        eclipticLongitudeB: 360,
        polarity: 'Negative',
        element: 'Water',
        planet: 'Jupiter',
        sexDrive: 'Feminine',
        hustle: 'Mutable',
        vibe: 'Adaptable',
        success: 'Changing',
      },
    ],
  });
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    console.log('Horoscope data seeded successfully');
    await prismadb.$disconnect();
  });
